### ISSUE TITLE
分享头条和评论无法完成了

### ISSUE THREAD

**Issue by hclasmn** [chr233/xhh_auto#4]
Run sh run.sh
Collecting pyxiaoheihe>=1.0.8
  Downloading pyxiaoheihe-1.0.9-py3-none-any.whl (40 kB)
Collecting requests
  Downloading requests-2.24.0-py2.py3-none-any.whl (61 kB)
Collecting toml
  Downloading toml-0.10.1-py2.py3-none-any.whl (19 kB)
Collecting rsa
  Downloading rsa-4.6-py3-none-any.whl (47 kB)
Collecting pyDes
  Downloading pyDes-2.0.1.tar.gz (9.9 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting chardet<4,>=3.0.2
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting pyasn1>=0.1.3
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Using legacy 'setup.py install' for pyDes, since package 'wheel' is not installed.
Installing collected packages: pyasn1, rsa, certifi, urllib3, idna, chardet, requests, pyDes, pyxiaoheihe, toml
    Running setup.py install for pyDes: started
    Running setup.py install for pyDes: finished with status 'done'
Successfully installed certifi-2020.6.20 chardet-3.0.4 idna-2.10 pyDes-2.0.1 pyasn1-0.4.8 pyxiaoheihe-1.0.9 requests-2.24.0 rsa-4.6 toml-0.10.1 urllib3-1.25.11
03:09:47 [INFO][Run]成功读取[1]个账号
03:09:47 [INFO][Run]==[1/1]=================================
03:09:48 [INFO][Run]任务[签到√|分享××|点赞√]
03:09:48 [INFO][14484460]获取首页新闻列表……
03:09:49 [INFO][14484460]获取[6]条内容
03:09:49 [INFO][14484460]分享新闻……
03:09:52 [INFO][14484460]感谢加入Xhh_Auto互助计划
03:09:56 [INFO][14484460]没有新粉丝
03:09:59 [INFO][14484460]获取[20]条动态
03:09:59 [INFO][14484460]点赞动态 47234822
03:10:01 [INFO][14484460]点赞动态 47315559
03:10:03 [INFO][14484460]点赞动态 47271009
03:10:05 [INFO][14484460]点赞动态 47197618
03:10:05 [INFO][14484460]点赞动态 47117061
03:10:06 [INFO][14484460]点赞动态 47077836
03:10:08 [INFO][14484460]点赞动态 46857681
03:10:10 [INFO][14484460]点赞动态 47239781
03:10:11 [INFO][14484460]点赞动态 47289499
03:10:13 [INFO][14484460]点赞动态 46842006
03:10:14 [INFO][14484460]点赞动态 46823465
03:10:15 [INFO][14484460]点赞动态 46759157
03:10:16 [INFO][14484460]点赞动态 47326380
03:10:17 [INFO][14484460]点赞动态 46655676
03:10:18 [INFO][14484460]点赞动态 46549509
03:10:19 [INFO][14484460]点赞动态 46540089
03:10:22 [INFO][14484460]点赞动态 46517994
03:10:22 [INFO][14484460]点赞动态 46486381
03:10:24 [INFO][14484460]点赞动态 47225695
03:10:26 [INFO][14484460]点赞动态 47322668
03:10:26 [INFO][Run]----------------------------------------
03:10:26 [INFO][Run]生成统计数据
03:10:26 [INFO][Run]昵称[hcl01] @14484460 
03:10:26 [INFO][Run]等级[13级]==>36%==>[14级]
03:10:26 [INFO][Run]盒币[17980]签到[69]天
03:10:26 [INFO][Run]等级[13级]==>36%==>[14级]
03:10:27 [INFO][Run]关注[56]粉丝[33]获赞[82]
03:10:27 [INFO][Run]签到[√]分享[××]点赞[√]
03:10:27 [INFO][Run]========================================
03:10:27 [INFO][Run]脚本版本:[0.91],核心版本:[1.0.9]
03:10:27 [INFO][Run]脚本耗时:[40.3586]s
03:10:27 [INFO][Run]检查脚本更新……
03:10:27 [INFO][Run]脚本已是最新,当前版本0.91
03:10:27 [INFO][Run]推送统计信息……
03:10:31 [INFO][Run]FTQQ推送成功
03:10:31 [INFO][Run]脚本执行完毕

**Comment by chr233** [comment]
新版已修复
